[package]
name = "csp-endpoint"
version = "0.1.0"
edition = "2024"
default-run = "csp-endpoint"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
env_logger = "0.11.10"
log = "0.4"
chrono = "0.4.44"
html-escape = "0.2.13"
# actix-web-helmet = "1.0.1"
#following are required for reqs.rs ONLY
#serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0"
#reqwest = { version = "0.13.3", features = ["json"] }

