[package]
name = "rust-api"
version = "0.1.0"
edition = "2024"
default-run = "rust-api"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
env_logger = "0.11.10"
log = "0.4"
#uuid = { version = "1", features = ["v4", "serde"] }
#chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13.3", features = ["json"] }